name: Publish Website
on:
  push:
    branches: [ master ]

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: Install-gem
      run: sudo gem install sass
    - name: Compile-Bulma
      run: sass --sourcemap=none ./css/bulma.scss:./css/bulma.css && echo Ran bulma compile
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://51.222.31.214/var/www/terraformersmc.com/public
        ftp-username: ubuntu
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        known-hosts: ${{ secrets.FTP_KNOWN_HOSTS }}
